<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Privacy Policy</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta name="keywords" content="" >
  <meta name="description" content="" >
  <meta name="revisit-after" content="2 days">
  <meta name="geolocation" content="India">
  <meta name="copyright" content="copyright &copy; 2020 Onlinerishta, All rights reserved">
  <meta name="robots" content="index, follow">
  <meta name="language" content="English">
  <meta name="google-site-verification" content="" />
<script src="https://kit.fontawesome.com/162db7f606.js" crossorigin="anonymous"></script>
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<link href="css/bootstrap-3.1.1.min.css" rel='stylesheet' type='text/css' />
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="js/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
<!-- Custom Theme files -->
<link href="css/style.css" rel='stylesheet' type='text/css' />
<link href='//fonts.googleapis.com/css?family=Oswald:300,400,700' rel='stylesheet' type='text/css'>
<link href='//fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>
<!----font-Awesome----->
<link href="css/font-awesome.css" rel="stylesheet"> 
<!----font-Awesome----->
<script>
$(document).ready(function(){
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>
</head>
<style>
    
    
h4, h5, h6, h1, h2, h3 {
    margin-top: 0;
    text-align: center;
    /* text-decoration-color: #bac6db; */
    /* background-color: darkcyan; */
}    
    
    
</style>


<body>
<!-- ============================  Navigation Start =========================== -->
 
<?php include 'head.php';?>
<!-- ============================  Navigation End ============================ -->




<div class="grid_3">
  <div class="container">
   <div class="breadcrumb1">
     <ul>
        <a href="index.php"><i class="fa fa-home home_1"></i></a>
        <span class="divider">&nbsp;|&nbsp;</span>
        <li class="current-page">Privacy Policy</li>
     </ul>
   </div>
   <div class="about">
 
 <div class="container margin-top">
	<div>
	      <h1><i class="fa fa-user-secret"></i> Privacy Policy - Onlinerishta</h1><hr>
	      <ul>
	      	<li>&#10149;The Onlinerishta Incorporated respect the privacy of the visitors to the Onlinerishta.in website, and take great care to protect your information.. This privacy policy tells you what information we collect from you, how we may use it and the steps we take to ensure that it is protected.</li>
	      </ul>
	</div>
	<div>
		<h2><i class="fa fa-user-circle"></i> General</h2><hr>
		<ul>
			<li>&#10149;This is electronic record in the of information technology act, 2000  and rules there are applicable .The documents is generated by the computer system not require physical or digital signature</li>
			<li>&#10149;This documents is published accordance with the provisions rule 3(1) of information technology rules, 2011 that require publishing  the rules and  regulations.privacy policy and terms of use for across or usage of onlinerishta.in</li>
			<li>&#10149;The domain name<a href="https://www.onlinerishta.in/"> www.onlinerishta.in</a> is owned and operated by Onlinerishta 
				a registered Company, limited by shares where such expression shall unless repugnant to the context thereof  , be deemed  to include its respective representatives, administrators , employee, directors, officers, agents and their successors and assigns.</li>
			<li>
				For the purpose of this  privacy policy wherever the context so  requires.
				<ol>
					<li>&#10149;Any person enter into the contract  and competent the contract who is binding the contract under indian contract 1872.</li>
					<li>&#10149;The  ‘we’ , use our shall mean the website and /or the company, as the context is required. </li>
					<li>&#10149;The terms ‘party &amp parties’ shall respectively be used to refer to the user and the company individually and collectively , as the context so requires.</li>
					<li>&#10149;The heading of each section in this policy are only for the purpose of organizing the various provisions under this policy in manner but shall not be used by either party to interpret the provisions contained in any manner. Further,specifically agreed by the parties that the headings shall not legal or contractual value.</li>
					<li>&#10149;The parties expressly agree that the company retains the sole and exclusive right to amend or modify the policy and the aforementioned terms without any prior permission or intimation to the user, and the user expressly agrees that any such amendments or modifications shall come into effect immediately . The user has a duty to periodically check the policy and terms and stay updated on their provisions and requirements. If the user continues to use the website following such a change , the user will be deemed to have consented  to any and all amendments /modifications made to the policy and terms .In so far as the user complies with the policy and terms ,he/she is granted a personal , non-exclusive ,non-transferable ,revocable ,limited privilege to enter , access and use the website.</li>
				</ol>
			</li>
		</ul>
	</div><br>
	
	
	<div>
		<h2><i class="fa fa-user-circle"></i>Protection of visitors information</h2><hr>
		<ul>
			<li>&#10149;In order to protect the information you provide to us by visiting our website we have implemented various security measures. Your personal information is contained behind secured networks and is only accessible by a limited number of people, who have special access rights and are required to keep the information confidential.Please keep in mind though that whenever you give out personal information online there is a risk that third parties may intercept and use that information. While Onlinerishta strives to protect its user's personal information and privacy, we cannot guarantee the security of any information you disclose online and you do so at your own risk.</li>
		</ul>
	</div>
	
	<br>
	<div>
		<h2><i class="fa fa-info-circle"></i> Collection of personal and other information</h2><hr>
		<ul>
			<li>&#10149;Personal information is collected by the company.which is provided by the user during registration on website but no limited to the user_name passwords,address , date of birth,email,age, nationality etc. images and other information uploaded by the user on the company's website uses the information which is given by the user.
			</i><li>&#10149;Company uses this information and provide the same information to other only for matrimonial Purpose.</li>
		  	<li>Certain information which  are tracked by the company from the its website . this information only can be used by the company .such information is given by the users is include the URL.</li>
			<li>If any user choose to buy a product and service from company’s website gather a personal information of who interested to buy a product and service in our company's website</li>
	    	<li>&#10149;Any information is given by the personal information  like phone number, email id is given by the company’s customer on the company's website. The company/ users collect the all the information and keep the new folder the company is awar all the information.</li>
			<li>&#10149;A company cannot provide any information without browse a website of the company. But certain information is provide by the company/users in certain area.company provide such information like registration, placing  order , fees description etc.</li>
			<li>Sometimes some information provide by the company/website  like (age,income , nationality,zip|_code) etc are remove from company’s website and benefit for the company.</li>
		<!--	<li>Company/website can request about the product /service which are purchased by the users on company's  website.  Company's website can also remove that names who is not satisfied from the company products and company published all the review is given by the users about company’ products and service.</li>-->
		</ul>
	</div>
	<div>
		<h2><i class="fa fa-share"></i> Sharing of personal information</h2><hr>
		<ul>
			<li>&#10149;Company’s website share personal information like name age marital status city and photograph as uploaded by user to the users who is already registered on company's website as it is matrimonial site.<br> According to our policy we also provide such right like user can also hide their photograph and can share with those website users who first talk and ask for photograph for matrimonial purpose </li>
			<li>&#10149;The company’s website has right to disclose and  share personal information to the users. If users is required his personal information.<br>Personal information of the users is also disclose to law enforcement officers,owner ,third party has right to such information is reasonably necessary to enforce the terms of policy.the third party protect the personal information of users from general public.</li>
			<li>&#10149;If a Company’s website merging with other companies  websites in the  event of recognition ,reconstructing of company’s business the company can share the personal information of users if required such business or new entity will continue to be bound with the terms and policy as may be  amended from time to time .</li>
		</ul>
	</div>


	
</div>
 
 
 
   	  </div>
   	  <div class="clearfix"> </div>
 	   </div>
	   <div class="clearfix"> </div>
	</div>
</div> 

<?php include 'footer.php' ?>
</body>
</html>	